name: Run playwright tests in docker

on:
  workflow_call:
    inputs:
      env:
        description: "Environment to run tests in"
        required: true
        type: string
      source:
        description: 'Source from which the E2E is triggered"'
        required: true
        type: string
    secrets:
      SQS_QUEUE_URL:
        description: "SQS queue url"
        required: true
      CAAS_SEARCH_API_KEY:
        description: "CAAS search api key"
        required: true

jobs:
  playwright_docker:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-skip-session-tagging: true
          role-to-assume: ${{ vars.GHA_ROLE_ARN }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Playwright tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from playwright
        env:
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
          CAAS_SEARCH_API_KEY: ${{ secrets.CAAS_SEARCH_API_KEY }}
          CAAS_SEARCH_ENDPOINT: ${{ vars.CAAS_SEARCH_ENDPOINT }}
          TEST_ENV: ${{ inputs.env || 'dev' }}
          TRIGGER_SOURCE: ${{ inputs.source || 'no-source' }}

      - uses: actions/upload-artifact@v3
        name: Upload report
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
